### ISSUE TITLE
LHS background

### ISSUE THREAD

**Issue by vishal7245** [vishal7245/CV#1]
LHS background is not dynamic and doesn't scale itself with page height.

**Comment by MostlyGenius** [comment]
I'd like to solve the issue, please assign it to me.

**Comment by MostlyGenius** [comment]
Hi,
Do you need 
1 .  Gap at bottom fixed.
2.  Overflow of content.
Please check picture for reference.
![LHS_FIX](https://user-images.githubusercontent.com/90004142/210463359-a1096cf2-9f80-45e1-a7d7-e6b2f3a5acee.png)

**Comment by vishal7245** [comment]
Gap at the bottom fixed,  I will readjust the overflow as I add. more content.
Thank you

**Comment by MostlyGenius** [comment]
Submitted fix.   If you need any changes or further help let me know.

**Comment by vishal7245** [comment]
Thanks, for sure

**Comment by vishal7245** [comment]
> Submitted fix. If you need any changes or further help let me know.

can you submit a pull request, I am not able to find where you have submitted the fix
